### ISSUE TITLE
Dropping of corrupted message leads to stuck orchestrations

### ISSUE THREAD

**Issue by sebastianburckhardt** [microsoft/durabletask-netherite#105]
Observed issues with corrupted message today:

```
System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type DurableTask.Netherite.Event. Start element 'c:Name' does not match end element 'c:N'. Line 1, position 488.
 ---> System.Xml.XmlException: Start element 'c:Name' does not match end element 'c:N'. Line 1, position 488.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, String res, String arg1, String arg2, String arg3)
   at System.Xml.XmlUTF8TextReader.ReadEndElement()
   at System.Xml.XmlUTF8TextReader.Read()
   at System.Xml.XmlBaseReader.ReadContentAsString()
   at System.Xml.XmlBaseReader.ReadElementContentAsString()
   at ReadTaskScheduledEventFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] )
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadTaskMessageFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] )
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadValueTupleOfTaskMessagestringKPngWuvwFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] )
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadArrayOfValueTupleOfTaskMessagestringKPngWuvwFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString , XmlDictionaryString , CollectionDataContract )
   at System.Runtime.Serialization.CollectionDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadActivityTransferReceivedFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] )
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(Stream stream)
   at DurableTask.Netherite.Serializer.DeserializeEvent(Stream stream) in C:\home\git\alt\src\DurableTask.Netherite\Util\Serializer.cs:line 58
   at DurableTask.Netherite.Packet.Deserialize[TEvent](Stream stream, TEvent& evt, Byte[] taskHubGuid) in C:\home\git\alt\src\DurableTask.Netherite\Events\Packet.cs:line 50
   at DurableTask.Netherite.FragmentationAndReassembly.Reassemble[TEvent](IEnumerable`1 earlierFragments, IEventFragment lastFragment) in C:\home\git\alt\src\DurableTask.Netherite\Util\FragmentationAndReassembly.cs:line 86
   at DurableTask.Netherite.ReassemblyState.Process(PartitionEventFragment evt, EffectTracker effects) in C:\home\git\alt\src\DurableTask.Netherite\PartitionState\ReassemblyState.cs:line 27
   at DurableTask.Netherite.EffectTracker.ProcessEffectOn(TrackedObject trackedObject) in C:\home\git\alt\src\DurableTask.Netherite\Abstractions\PartitionState\EffectTracker.cs:line 80
```

**Comment by sebastianburckhardt** [comment]
Kusto query:
// zoom in on second error
database("wawsprod").DurableFunctionsEvents
| where TIMESTAMP>= datetime(2022-01-11 13:30:00) and TIMESTAMP <= datetime(2022-01-11 13:54:00)
| where AppName== "functionssb3"
| where PartitionId == 1 or PartitionId == ""
| where TaskName == "PartitionProgress" or TaskName == "PartitionWarning" or TaskName == "PartitionError" or TaskName == "FasterProgress"
| project TIMESTAMP, Level, EventIpAddress, PartitionId, TaskName, Transition, Details, Context, Message, TerminatesPartition
| sort by TIMESTAMP asc

**Comment by sebastianburckhardt** [comment]
Appears to be caused by duplication of a fragmented event:
```
// check eventhubs
database("wawsprod").DurableFunctionsEvents
| where TIMESTAMP>= datetime(2022-01-11 13:34:01.4145300) and TIMESTAMP <= datetime(2022-01-11 13:36:12.7411701)
| where AppName== "functionssb3"
| where EventIpAddress == "10.20.0.164"
| where PartitionId == 1 or PartitionId == ""
    | where TaskName startswith "EventHubs"
    | where Details contains "EventHubsSender partitions/1 "
    | project TIMESTAMP, Level = iff(Details contains "sent fragment" and Details contains "02F2022-01-11T13:33:23.8568514ZP01", 4, 5), EventIpAddress, PartitionId, TaskName, Details
    | sort by TIMESTAMP asc
    
 

TIMESTAMP	Level	EventIpAddress	TaskName	Details
2022-01-11 13:34:01.4145300	4	10.20.0.164	EventHubsDebug	EventHubsSender partitions/1 sent fragment 0/5 (683269 bytes) id=02F2022-01-11T13:33:23.8568514ZP01I0
2022-01-11 13:34:52.0057634	5	10.20.0.164	EventHubsWarning	EventHubsSender partitions/1 failed to send
2022-01-11 13:34:57.5840571	5	10.20.0.164	EventHubsWarning	EventHubsSender partitions/1 has confirmed 0, requeued 33, dropped 0 outbound events
2022-01-11 13:35:54.8507562	5	10.20.0.164	EventHubsWarning	EventHubsSender partitions/1 failed to send
2022-01-11 13:36:00.0777972	5	10.20.0.164	EventHubsWarning	EventHubsSender partitions/1 has confirmed 0, requeued 33, dropped 0 outbound events
2022-01-11 13:36:12.7411701	4	10.20.0.164	EventHubsDebug	EventHubsSender partitions/1 sent fragment 0/5 (683269 bytes) id=02F2022-01-11T13:33:23.8568514ZP01I0
```
