### ISSUE TITLE
Assertion violations

### ISSUE THREAD

**Issue by sebastianburckhardt** [microsoft/durabletask-netherite#218]
Observed an assertion violation triggering in the Load Publisher after recovery.

[2023-01-23T20:21:52.552Z] Part04 !!! Assertion Failed: instance count does not match index size in    at System.Environment.get_StackTrace()
[2023-01-23T20:21:52.553Z]    at DurableTask.Netherite.Partition.Assert(Boolean condition, String message) in D:\git\durabletask-netherite\src\DurableTask.Netherite\OrchestrationService\Partition.cs:line 164
[2023-01-23T20:21:52.559Z]    at DurableTask.Netherite.StatsState.UpdateLoadInfo(PartitionLoadInfo info) in D:\git\durabletask-netherite\src\DurableTask.Netherite\PartitionState\StatsState.cs:line 38
[2023-01-23T20:21:52.560Z]    at DurableTask.Netherite.Faster.StoreWorker.UpdateLoadInfo() in D:\git\durabletask-netherite\src\DurableTask.Netherite\StorageLayer\Faster\StoreWorker.cs:line 209
[2023-01-23T20:21:52.561Z]    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)

**Comment by sebastianburckhardt** [comment]
Found a bug where the wrong object is locked, causing race conditions inside the in-memory index. This assertion error is likely a consequence of that.

Should be fixed with #219.
