### ISSUE TITLE
Partitions hang after changing plan or InstanceCacheSizeMB

### ISSUE THREAD

**Issue by sebastianburckhardt** [microsoft/durabletask-netherite#234]
As reported in #232, partitions can go into an infinite loop where they fail to recover, which means the task hub becomes unresponsive.  

## Symptoms
The function app appears unresponsive and the logs show errors `System.ArgumentException: Destination array was not long enough` with stack traces like the following:

```
2023-03-15T20:00:15.7493912Z PD1MDWK000KNH [DurableTask.Netherite.FasterStorage]s4 Part11 !!! Faster Storage Error : loading checkpoint : System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at FASTER.core.FasterKV`2.SetRecoveryPageRanges(HybridLogCheckpointInfo recoveredHLCInfo, Int32 numPagesToPreload, Int64 fromAddress, Int64& tailAddress, Int64& headAddress, Int64& scanFromAddress)
   at FASTER.core.FasterKV`2.InternalRecoverAsync(IndexCheckpointInfo recoveredICInfo, HybridLogCheckpointInfo recoveredHLCInfo, Int32 numPagesToPreload, Boolean undoNextVersion, Int64 recoverTo, CancellationToken cancellationToken)
   at DurableTask.Netherite.Faster.FasterKV.RecoverAsync() in D:\git\durabletask-netherite\src\DurableTask.Netherite\StorageLayer\Faster\FasterKV.cs:line 252
   at DurableTask.Netherite.Faster.PartitionStorage.TerminationWrapper[T](Task`1 what)
   at DurableTask.Netherite.Faster.PartitionStorage.CreateOrRestoreAsync(Partition partition, IPartitionErrorHandler errorHandler, String inputQueueFingerprint) in D:\git\durabletask-netherite\src\DurableTask.Netherite\StorageLayer\Faster\PartitionStorage.cs:line 178
```

## Cause

It appears that as an uninteded side effect of reducing the default segment size (#230), the FASTER component can now run into trouble when its memory size parameter does not match the original value when the task hub is first created. This then causes the partition to repeatedly fail to load, which means the task hub is unresponsive.

Changing the number of cores on a machine, or changing the parameter InstanceCacheSizeMB, can trigger this issue, until we fix the code.

## Workarounds

Going back to the same plan (processor count) and the same `InstanceCacheSizeMB` as when the task hub was first created avoids this issue.

**Comment by sebastianburckhardt** [comment]
Fix was released with 1.3.3.
