### ISSUE TITLE
New exceptions - 100 orchestrators and 1000 activities -  Part00 !!! Encountered exception on Reassembly

### ISSUE THREAD

**Issue by ericleigh007** [microsoft/durabletask-netherite#238]
Encountering new exceptions in attempting scale tests with Netherite.  This is previous to 1.3.3.
The test is very similar to the previous one for Part10 exception, but we have 100 orchestrators and 1000 activities each.

```
2023-03-18T00:02:51Z   [Error]   Part00 !!! Encountered exception on Reassembly (0 pending) when applying update event PartitionEventFragment 460800 eventId=02F2023-03-18T00:00:08.7306490ZP00I4 in ProcessUpdate: System.Collections.Generic.KeyNotFoundException: The given key '02F2023-03-18T00:00:08.7306490ZP00' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DurableTask.Netherite.ReassemblyState.Process(PartitionEventFragment evt, EffectTracker effects) in /_/src/DurableTask.Netherite/PartitionState/ReassemblyState.cs:line 99
   at DurableTask.Netherite.EffectTracker.ProcessEffectOn(TrackedObject trackedObject) in /_/src/DurableTask.Netherite/Abstractions/PartitionState/EffectTracker.cs:line 80 terminatePartition=False
2023-03-18T00:02:51Z   [Error]   Part00 !!! Encountered exception on Reassembly (0 pending) when applying update event PartitionEventFragment 382214 last eventId=02F2023-03-18T00:00:08.7306490ZP00I5 in ProcessUpdate: System.Collections.Generic.KeyNotFoundException: The given key '02F2023-03-18T00:00:08.7306490ZP00' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DurableTask.Netherite.ReassemblyState.Process(PartitionEventFragment evt, EffectTracker effects) in /_/src/DurableTask.Netherite/PartitionState/ReassemblyState.cs:line 61
   at DurableTask.Netherite.EffectTracker.ProcessEffectOn(TrackedObject trackedObject) in /_/src/DurableTask.Netherite/Abstractions/PartitionState/EffectTracker.cs:line 80 terminatePartition=False
2023-03-18T00:02:53Z   [Warning]   BandConductorOrchestrator 8595d048c9e44b4fb83a237ae8a31afe ad0b0921-fdbc-40b3-9f30-94c43742ce90 got 85830 of 100000 documents
2023-03-18T00:03:06Z   [Warning]   EventHubsSender partitions/11 failed to send
2023-03-18T00:03:08Z   [Warning]   BandConductorOrchestrator 8595d048c9e44b4fb83a237ae8a31afe ad0b0921-fdbc-40b3-9f30-94c43742ce90 got 85830 of 100000 documents
```

**Comment by ericleigh007** [comment]
After 1.3.3, I can no longer duplicate this.  Great work!
