### ISSUE TITLE
New exception with 100 orchestrators and 1000 activities - Part11 !!! Encountered exception on Reassembly

### ISSUE THREAD

**Issue by ericleigh007** [microsoft/durabletask-netherite#239]
This one is also encountered with 100 orchestrators and 1000 activities

```
2023-03-18T00:03:10Z   [Error]   Part11 !!! Encountered exception on Reassembly (1 pending) when applying update event PartitionEventFragment 31153 last eventId=00F2023-03-18T00:00:04.3369688ZP11I8 in ProcessUpdate: System.Collections.Generic.KeyNotFoundException: The given key '00F2023-03-18T00:00:04.3369688ZP11' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DurableTask.Netherite.ReassemblyState.Process(PartitionEventFragment evt, EffectTracker effects) in /_/src/DurableTask.Netherite/PartitionState/ReassemblyState.cs:line 61
   at DurableTask.Netherite.EffectTracker.ProcessEffectOn(TrackedObject trackedObject) in /_/src/DurableTask.Netherite/Abstractions/PartitionState/EffectTracker.cs:line 80 terminatePartition=False
```

**Comment by ericleigh007** [comment]
After 1.3.3, this I can no longer duplicate.  Great!
