### ISSUE TITLE
`BlobNotFound` error when running the DTFx sample

### ISSUE THREAD

**Issue by aelij** [microsoft/durabletask-netherite#279]
Getting the following error after setting the env vars and `dotnet run` from a fresh repo clone:

```
fail: DurableTask.Netherite[0] Part01 !!! storage operation PageBlobClient.CreateAsync (CreateDevice) failed on attempt 2 blob=bc713003-4f62-4acd-a566-f383a8b2e248/p01/index-checkpoints/ede4be65-f0b1-4794-8e15-9a20479ba713/ht.dat.0 in PageBlobClient.CreateAsync: Azure.RequestFailedException: Service request failed. Status: 404 (The specified blob does not exist.) ErrorCode: BlobNotFound
   at Azure.Storage.Blobs.BlobRestClient.GetPropertiesAsync(String snapshot, String versionId, Nullable`1 timeout, String leaseId, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, CancellationToken cancellationToken) 
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.GetPropertiesInternal(BlobRequestConditions conditions, Boolean async, CancellationToken cancellationToken, String operationName)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.GetPropertiesAsync(BlobRequestConditions conditions, CancellationToken cancellationToken)
   at DurableTask.Netherite.Faster.BlobEntry.<>c__DisplayClass13_0.<<CreateAsync>b__1>d.MoveNext() in /_/src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/BlobEntry.cs:line 88
 --- End of stack trace from previous location ---
   at DurableTask.Netherite.Faster.BlobManager.PerformWithRetriesAsync(SemaphoreSlim semaphore, Boolean requireLease, String name, String intent, String data, String target, Int32 expectedLatencyBound, Boolean isCritical, Func`2 operationAsync, Func`1 readETagAsync) in /_/src/DurableTask.Netherite/StorageLayer/Faster/AzureBlobs/StorageOperations.cs:line 52 terminatePartition=True
```

**Comment by sebastianburckhardt** [comment]
I think this has been fixed. Let us know if you are still seeing this error.
