### ISSUE TITLE
Non-Deterministic workflow detected ... current replay execution hasn't (yet?) scheduled this task

### ISSUE THREAD

**Issue by jbarntish** [microsoft/durabletask-netherite#297]
Hi all,

We have recently hit this issue when executing sub orchestrations. Wondering if anyone has seen this before and could provide some guidance. 

> Note: Adding this to the netherite repo since the netherite backend is in use. If you think this is more related to Durable Task I will move it.

What's odd to me: re-running from the start of the main orchestrator with the same data set does not produce the issue. No updates were made to the function app while the orchestration was running, and the activity it is calling is deterministic and runs without an issue. 

We've seen this one other time, almost a month ago, but it occurred during a different activity. 

Given all that: is this simply some kind of transient issue that should be handled by a retry policy when calling sub orchestrators?

```
Orchestrator function 'MainOrchestrator' failed: The orchestrator function 'FooOrchestrator' failed: "Failed to deserialize exception from TaskActivity: Unhandled exception while executing orchestration: DurableTask.Core.Exceptions.NonDeterministicOrchestrationException: Non-Deterministic workflow detected: A previous execution of this orchestration scheduled an activity task with sequence ID 1 and name 'HasFaultsByBatchAndSerial' (version ''), but the current replay execution hasn't (yet?) scheduled this task. Was a change made to the orchestrator code after this instance had already started running?
at DurableTask.Core.TaskOrchestrationContext.HandleTaskScheduledEvent(TaskScheduledEvent scheduledEvent) in /_/src/DurableTask.Core/TaskOrchestrationContext.cs:line 275
at DurableTask.Core.TaskOrchestrationExecutor.<ExecuteCore>g__ProcessEvents|11_0(IEnumerable`1 events) in /_/src/DurableTask.Core/TaskOrchestrationExecutor.cs:line 115
at DurableTask.Core.TaskOrchestrationExecutor.ExecuteCore(IEnumerable`1 pastEvents, IEnumerable`1 newEvents) in /_/src/DurableTask.Core/TaskOrchestrationExecutor.cs:line 123
at DurableTask.Core.TaskOrchestrationContext.HandleTaskScheduledEvent(TaskScheduledEvent scheduledEvent) in /_/src/DurableTask.Core/TaskOrchestrationContext.cs:line 275
at DurableTask.Core.TaskOrchestrationExecutor.<ExecuteCore>g__ProcessEvents|11_0(IEnumerable`1 events) in /_/src/DurableTask.Core/TaskOrchestrationExecutor.cs:line 115
at DurableTask.Core.TaskOrchestrationExecutor.ExecuteCore(IEnumerable`1 pastEvents, IEnumerable`1 newEvents) in /_/src/DurableTask.Core/TaskOrchestrationExecutor.cs:line 123". See the function execution logs for additional details.
```

Worth noting: based on the messaging I was able to trace this exception back to some base code in the Durable Task framework. It seems like something didnt get registered properly somewhere: [Durable Task Code](https://github.com/Azure/durabletask/blob/e824412134eeb1bde93426d7bbe5ae50fd60ce64/src/DurableTask.Core/TaskOrchestrationContext.cs#L270C26-L270C26)

```csharp
public void HandleTaskScheduledEvent(TaskScheduledEvent scheduledEvent)
        {
            int taskId = scheduledEvent.EventId;
            if (!this.orchestratorActionsMap.ContainsKey(taskId))
            {
                throw new NonDeterministicOrchestrationException(scheduledEvent.EventId,
                    $"A previous execution of this orchestration scheduled an activity task with sequence ID {taskId} and name "
                    + $"'{scheduledEvent.Name}' (version '{scheduledEvent.Version}'), but the current replay execution hasn't "
                    + "(yet?) scheduled this task. Was a change made to the orchestrator code after this instance had already "
                    + "started running?");
            }

```

**Comment by sebastianburckhardt** [comment]
Nondeterminism in orchestrations is most often a consequence of not following the coding rules that are required.
So, the first step when encountering such exceptions is to double-check whether your code violates any of these rules:

https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-code-constraints?tabs=csharp
