### ISSUE TITLE
Sudden Netherite "Client request timed out" exception

### ISSUE THREAD

**Issue by thegrekle** [microsoft/durabletask-netherite#306]
Early this morning one of our production durable functions app started failing with the following error.  The error resulted in essentially a complete failure of our production application for all of our customers.

```
Error: The operation failed with an unexpected status code: 500. Details: {"Message":"Something went wrong while processing your request","ExceptionMessage":"Client request timed out.","ExceptionType":"System.TimeoutException"
```

After finding the message, I checked the eventhub namespace and saw no throttled messages.  I stopped and then started the function app which seemed to clear the error and things started processing again.  

From what I can tell via logs, our instances were running the extensionBundle 4.8.0 which mentions a fix for #272 which reads very similar to the issue we encountered this morning.  However, I saw no evidence of any eventhub throttling.

I can provide any additional information that is needed to help understand and prevent this.  

The errors began at Sept 17, 2:57:50 AM CDT.  

Thank you

**Comment by thegrekle** [comment]
Here's the full stack trace in case that's helpful.  

```
Error: The operation failed with an unexpected status code: 500. Details: {"Message":"Something went wrong while processing your request","ExceptionMessage":"Client request timed out.","ExceptionType":"System.TimeoutException","StackTrace":"   at DurableTask.Netherite.Client.CreateTaskOrchestrationAsync(UInt32 partitionId, TaskMessage creationMessage, OrchestrationStatus[] dedupeStatuses) in /_/src/DurableTask.Netherite/OrchestrationService/Client.cs:line 469\r\n   at DurableTask.Netherite.NetheriteOrchestrationService.DurableTask.Core.IOrchestrationServiceClient.CreateTaskOrchestrationAsync(TaskMessage creationMessage, OrchestrationStatus[] dedupeStatuses) in /_/src/DurableTask.Netherite/OrchestrationService/NetheriteOrchestrationService.cs:line 594\r\n   at DurableTask.Core.TaskHubClient.InternalCreateOrchestrationInstanceWithRaisedEventAsync(String orchestrationName, String orchestrationVersion, String orchestrationInstanceId, Object orchestrationInput, IDictionary`2 orchestrationTags, OrchestrationStatus[] dedupeStatuses, String eventName, Object eventData, Nullable`1 startAt) in /_/src/DurableTask.Core/TaskHubClient.cs:line 614\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationClient.StartNewAsync[T](String orchestratorFunctionName, String instanceId, T input) in D:\\a\\_work\\1\\s\\src\\WebJobs.Extensions.DurableTask\\ContextImplementations\\DurableClient.cs:line 210\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleStartOrchestratorRequestAsync(HttpRequestMessage request, String functionName, String instanceId) in D:\\a\\_work\\1\\s\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 875\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleRequestAsync(HttpRequestMessage request) in D:\\a\\_work\\1\\s\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 306"}
    at DurableOrchestrationClient.createGenericError (C:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:612:16)
    at DurableOrchestrationClient.<anonymous> (C:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:404:44)
    at Generator.next (<anonymous>)
    at fulfilled (C:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by sebastianburckhardt** [comment]
Unfortunately, the client request timeouts can have many reasons. It basically means the client did not receive a response from the partition in time; but it contains no information about why. Usually the next step is to take a look at the logs for the target partition.

Is this running in a consumption or premium plan? If so, I can take a look at the trace in our internal telemetry if you tell me the appname.

**Comment by thegrekle** [comment]
iothubprod

Thank you
