### ISSUE TITLE
Partition becomes unresponsive because event batch blob was deleted prematurely

### ISSUE THREAD

**Issue by alexjebens** [microsoft/durabletask-netherite#363]
We are seeing that partitions are unable to start because an eh-batch file was missing. 

At the time that these messages were logged the DurableTaskPartitions table showed that partition 8 failed to start (stuck outbox messages in all other partitions, timestamp multiple hours old).

FASTER state and the eventhub checkpoint data could be inconsistent/divergent because the eventhub checkpoint data is in separate blobs ({TaskHub Guid}/eh-checkpoints/). Since the Eventhubs Processor Library used by Netherite has (at least in some version) the possibility to Provide custom checkpoint data persistence, the data could be persisted in FASTER along with the other state data.

```
2024-03-01T14:15:51.502 [Error] EventHubsProcessor partitions/8 failed to read blob eh-batches/2024-03-01T09:32:29.2095178Z-588D70E4 for #278806: Azure.RequestFailedException: The specified blob does not exist.
RequestId:299e2c6a-601e-0026-07e2-6b266d000000
Time:2024-03-01T14:15:51.1777912Z
Status: 404 (The specified blob does not exist.)
ErrorCode: BlobNotFound
 
Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:299e2c6a-601e-0026-07e2-6b266d000000
Time:2024-03-01T14:15:51.1777912Z</Message></Error>
 
Headers:
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 299e2c6a-601e-0026-07e2-6b266d000000
x-ms-client-request-id: 285e754f-e195-4438-926f-ce4cdcf3868c
x-ms-version: 2022-11-02
x-ms-error-code: BlobNotFound
Date: Fri, 01 Mar 2024 14:15:50 GMT
Content-Length: 215
Content-Type: application/xml
 
   at Azure.Storage.Blobs.BlobRestClient.DownloadAsync(String snapshot, String versionId, Nullable`1 timeout, String range, String leaseId, Nullable`1 rangeGetContentMD5, Nullable`1 rangeGetContentCRC64, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions validationOptions, Int64 startOffset, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingInternal(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions transferValidationOverride, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingDirect(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions transferValidationOverride, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentInternal(BlobRequestConditions conditions, IProgress`1 progressHandler, HttpRange range, DownloadTransferValidationOptions transferValidationOverride, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentAsync(BlobRequestConditions conditions, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentAsync(CancellationToken cancellationToken)
   at DurableTask.Netherite.EventHubsTransport.BlobBatchReceiver`1.ReceiveEventsAsync(Byte[] guid, IEnumerable`1 hubMessages, CancellationToken token, MutableLong nextPacketToReceive)+MoveNext() in /_/src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs:line 118
2024-03-01T14:15:51.504 [Information] @processexecutor@000005: Executing '@processexecutor@000005' orchestration logic
2024-03-01T14:15:51.508 [Information] Executing 'ProcessExecutor' (Reason='(null)', Id=8e152620-b431-41b1-81d7-0711dad8734e)
2024-03-01T14:15:51.508 [Information] @processexecutor@000005: Function 'processexecutor (Entity)' started. IsReplay: False. Input: (162288 bytes). State: Started. RuntimeStatus: Running. HubName: sapmpn. AppName: func-space-fo-sap-messageprocessor-qas. SlotName: Production. ExtensionVersion: 2.13.1. SequenceNumber: 8. TaskEventId: -1
2024-03-01T14:15:51.509 [Information] @processexecutor@000012: Executing '@processexecutor@000012' orchestration logic
2024-03-01T14:15:51.510 [Information] Executing 'ProcessExecutor' (Reason='(null)', Id=efb37fe7-d10c-4240-87bb-cdedf38b9df2)
2024-03-01T14:15:51.510 [Information] @processexecutor@000012: Function 'processexecutor (Entity)' started. IsReplay: False. Input: (209644 bytes). State: Started. RuntimeStatus: Running. HubName: sapmpn. AppName: func-space-fo-sap-messageprocessor-qas. SlotName: Production. ExtensionVersion: 2.13.1. SequenceNumber: 9. TaskEventId: -1
2024-03-01T14:15:51.510 [Information] @processexecutor@000009: Executing '@processexecutor@000009' orchestration logic
2024-03-01T14:15:51.511 [Information] Executing 'ProcessExecutor' (Reason='(null)', Id=422c2408-eefe-44fa-828b-004c6361e2c1)
2024-03-01T14:15:51.511 [Information] @processexecutor@000009: Function 'processexecutor (Entity)' started. IsReplay: False. Input: (130604 bytes). State: Started. RuntimeStatus: Running. HubName: sapmpn. AppName: func-space-fo-sap-messageprocessor-qas. SlotName: Production. ExtensionVersion: 2.13.1. SequenceNumber: 10. TaskEventId: -1
2024-03-01T14:15:51.618 [Information] Enter Business Partner Search Data Service
2024-03-01T14:15:51.620 [Trace] Batch Size Business Partner Search Data adjusted.
2024-03-01T14:15:51.620 [Trace] Mapping Business Partner Search Data
2024-03-01T14:15:51.620 [Trace] Mapping Business Partner Search Data
2024-03-01T14:15:51.714 [Error] EventHubsProcessor partitions/8(1) encountered an exception while processing packets : Azure.RequestFailedException: The specified blob does not exist.
RequestId:299e2c6a-601e-0026-07e2-6b266d000000
Time:2024-03-01T14:15:51.1777912Z
Status: 404 (The specified blob does not exist.)
ErrorCode: BlobNotFound
 
Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:299e2c6a-601e-0026-07e2-6b266d000000
Time:2024-03-01T14:15:51.1777912Z</Message></Error>
 
Headers:
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 299e2c6a-601e-0026-07e2-6b266d000000
x-ms-client-request-id: 285e754f-e195-4438-926f-ce4cdcf3868c
x-ms-version: 2022-11-02
x-ms-error-code: BlobNotFound
Date: Fri, 01 Mar 2024 14:15:50 GMT
Content-Length: 215
Content-Type: application/xml
 
   at Azure.Storage.Blobs.BlobRestClient.DownloadAsync(String snapshot, String versionId, Nullable`1 timeout, String range, String leaseId, Nullable`1 rangeGetContentMD5, Nullable`1 rangeGetContentCRC64, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions validationOptions, Int64 startOffset, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingInternal(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions transferValidationOverride, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingDirect(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions transferValidationOverride, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentInternal(BlobRequestConditions conditions, IProgress`1 progressHandler, HttpRange range, DownloadTransferValidationOptions transferValidationOverride, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentAsync(BlobRequestConditions conditions, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentAsync(CancellationToken cancellationToken)
   at DurableTask.Netherite.EventHubsTransport.BlobBatchReceiver`1.ReceiveEventsAsync(Byte[] guid, IEnumerable`1 hubMessages, CancellationToken token, MutableLong nextPacketToReceive)+MoveNext() in /_/src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs:line 118
   at DurableTask.Netherite.EventHubsTransport.BlobBatchReceiver`1.ReceiveEventsAsync(Byte[] guid, IEnumerable`1 hubMessages, CancellationToken token, MutableLong nextPacketToReceive)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at DurableTask.Netherite.EventHubsTransport.EventHubsProcessor.Microsoft.Azure.EventHubs.Processor.IEventProcessor.ProcessEventsAsync(PartitionContext context, IEnumerable`1 packets) in /_/src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs:line 435
   at DurableTask.Netherite.EventHubsTransport.EventHubsProcessor.Microsoft.Azure.EventHubs.Processor.IEventProcessor.ProcessEventsAsync(PartitionContext context, IEnumerable`1 packets) in /_/src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs:line 435
2024-03-01T14:15:51.723 [Error] Part08 !!! Encountered exception while processing events in IEventProcessor.ProcessEventsAsync: Azure.RequestFailedException: The specified blob does not exist.
RequestId:299e2c6a-601e-0026-07e2-6b266d000000
Time:2024-03-01T14:15:51.1777912Z
Status: 404 (The specified blob does not exist.)
ErrorCode: BlobNotFound
 
Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:299e2c6a-601e-0026-07e2-6b266d000000
Time:2024-03-01T14:15:51.1777912Z</Message></Error>
 
Headers:
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 299e2c6a-601e-0026-07e2-6b266d000000
x-ms-client-request-id: 285e754f-e195-4438-926f-ce4cdcf3868c
x-ms-version: 2022-11-02
x-ms-error-code: BlobNotFound
Date: Fri, 01 Mar 2024 14:15:50 GMT
Content-Length: 215
Content-Type: application/xml
 
   at Azure.Storage.Blobs.BlobRestClient.DownloadAsync(String snapshot, String versionId, Nullable`1 timeout, String range, String leaseId, Nullable`1 rangeGetContentMD5, Nullable`1 rangeGetContentCRC64, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions validationOptions, Int64 startOffset, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingInternal(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions transferValidationOverride, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingDirect(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions transferValidationOverride, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentInternal(BlobRequestConditions conditions, IProgress`1 progressHandler, HttpRange range, DownloadTransferValidationOptions transferValidationOverride, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentAsync(BlobRequestConditions conditions, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadContentAsync(CancellationToken cancellationToken)
   at DurableTask.Netherite.EventHubsTransport.BlobBatchReceiver`1.ReceiveEventsAsync(Byte[] guid, IEnumerable`1 hubMessages, CancellationToken token, MutableLong nextPacketToReceive)+MoveNext() in /_/src/DurableTask.Netherite/TransportLayer/EventHubs/BlobBatchReceiver.cs:line 118
   at DurableTask.Netherite.EventHubsTransport.BlobBatchReceiver`1.ReceiveEventsAsync(Byte[] guid, IEnumerable`1 hubMessages, CancellationToken token, MutableLong nextPacketToReceive)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at DurableTask.Netherite.EventHubsTransport.EventHubsProcessor.Microsoft.Azure.EventHubs.Processor.IEventProcessor.ProcessEventsAsync(PartitionContext context, IEnumerable`1 packets) in /_/src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs:line 435
   at DurableTask.Netherite.EventHubsTransport.EventHubsProcessor.Microsoft.Azure.EventHubs.Processor.IEventProcessor.ProcessEventsAsync(PartitionContext context, IEnumerable`1 packets) in /_/src/DurableTask.Netherite/TransportLayer/EventHubs/EventHubsProcessor.cs:line 435 terminatePartition=True
2024-03-01T14:15:51.753 [Information] Part08 Terminated partition after 581.00ms
```

**Comment by sebastianburckhardt** [comment]
I believe the problem is that the blob was deleted too early. I will investigate this further and develop a fix.

In the meantime, as a workaround to get your taskhub running again, you can **manually delete the ‘partitions’ event hub**, from the portal:
![image](https://github.com/microsoft/durabletask-netherite/assets/6415760/c4891989-a02a-440f-8eb8-e52f1e105156)

This deletes all the in-flight messages, and each partition then sends those messages again (so no data is actually lost). Based on my understanding this should resolve your situation. Of course it is not a long term solution, just a quick workaround.

**Comment by sebastianburckhardt** [comment]
I found a bug in how  batch persistence (i.e. when is it safe to remove a batch blob from storage) is being tracked in  `BlobBatchReceiver.BlobDeletions`. This causes blob batches to be deleted too early in some situations, which causes the error you are seeing.

**Comment by alexjebens** [comment]
> I believe the problem is that the blob was deleted too early. I will investigate this further and develop a fix.
> 
> In the meantime, as a workaround to get your taskhub running again, you can **manually delete the ‘partitions’ event hub**, from the portal: ![image](https://private-user-images.githubusercontent.com/6415760/313862273-c4891989-a02a-440f-8eb8-e52f1e105156.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NzQxNTUsIm5iZiI6MTcxMDg3Mzg1NSwicGF0aCI6Ii82NDE1NzYwLzMxMzg2MjI3My1jNDg5MTk4OS1hMDJhLTQ0MGYtOGViOC1lNTJmMWUxMDUxNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMTg0NDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjQyMWZhNTliZWU1OWY4NjYyOGVmNjRlNzhiNDJiMDBkMDFhZGNjNzM1OTIyNjhjMTAyODdmOWI5MTU5MmFhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v16a4_jpCpeqt5fY9JFFgOBZT5caq12tiqKZ9jUxw70)
> 
> This deletes all the in-flight messages, and each partition then sends those messages again (so no data is actually lost). Based on my understanding this should resolve your situation. Of course it is not a long term solution, just a quick workaround.

Thank you for your prompt response. I have to tell you though, from personal experience, that deleting the partitions eventhub does lead to lost messages

**Comment by sebastianburckhardt** [comment]
> I have to tell you though, from personal experience, that deleting the partitions eventhub does lead to lost messages

Perhaps I should have qualified this a bit. Yes, it is possible to lose messages that are in flight from clients to partitions, or from partitions to clients. These messages are generally considered unreliable (e.g. they are also subject to timeouts). However, any state on the partitions, and all messages that are traveling between partitions, are preserved.
