### ISSUE TITLE
Purging and getting instances with DurableTaskClient in dotnet-isolated runtime

### ISSUE THREAD

**Issue by talhanaveedcoop** [microsoft/durabletask-netherite#372]
I am using the Durable task client (Microsoft.DurableTask.Client.DurableTaskClient) in dotnet isolated runtime. I want to purge instances of durable functions that have completed or failed and also I want to see how many instances are in running state. For this I am using the following code
![image](https://github.com/microsoft/durabletask-netherite/assets/141133636/ae40468f-553e-46cb-b26a-2a170ab6d848)

![image](https://github.com/microsoft/durabletask-netherite/assets/141133636/d024b4f4-bf08-493f-8571-b936fc979a76)

Both there statements were working with Azure storage but they are not working with netherite. I get the following exception saying that the action is not supported when I try to purge
![image](https://github.com/microsoft/durabletask-netherite/assets/141133636/7356d196-f6d7-47fe-a0f7-5aac34b5fce0)

and I get a GRPC exception when I try to fetch all instances. 
![image](https://github.com/microsoft/durabletask-netherite/assets/141133636/fa8e5dc3-4313-4424-8310-fafb3b1c4da6)

are these actions not supported for netherite and dotnet isolated?

**Comment by dunxbc** [comment]
I've encountered this issue as well. Rolling back `Microsoft.Azure.Functions.Worker.Extensions.DurableTask` to 1.1.0 fixes the issue, it appears to be a regression in v1.1.2 of that package.

**Comment by talhanaveedcoop** [comment]
Rolling back to 1.1.0 solves the purging issue but there is still an issue with get instance states. The code is as follows

```
var instances = await client.GetAllInstancesAsync(new OrchestrationQuery
{ 
    CreatedFrom = DateTimeOffset.MinValue,
    CreatedTo = DateTimeOffset.Now,
    Statuses = new List<OrchestrationRuntimeStatus>
{
    OrchestrationRuntimeStatus.Running,
    OrchestrationRuntimeStatus.Pending,
}
}).ToListAsync();
```

But I get the following grpc exception

![image](https://github.com/microsoft/durabletask-netherite/assets/141133636/e6efbbdc-b756-4bdb-8345-84e11854f59a)

```
[14:13:03 ERR] Error in bong trigger: Status(StatusCode="Unknown", Detail="Exception was thrown by handler."), Message: Status(StatusCode="Unknown", Detail="Exception was thrown by handler."), InnerException: null
[2024-04-11T12:13:03.926Z] Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
[2024-04-11T12:13:03.928Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableTaskClient.<>c__DisplayClass18_0.<<GetAllInstancesAsync>b__0>d.MoveNext()
[2024-04-11T12:13:03.929Z] --- End of stack trace from previous location ---
[2024-04-11T12:13:03.930Z]    at Microsoft.DurableTask.Pageable.FuncAsyncPageable`1.AsPagesCore(String continuationToken, Nullable`1 pageSizeHint, CancellationToken cancellation)+MoveNext()
[2024-04-11T12:13:03.931Z]    at Microsoft.DurableTask.Pageable.FuncAsyncPageable`1.AsPagesCore(String continuationToken, Nullable`1 pageSizeHint, CancellationToken cancellation)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
[2024-04-11T12:13:03.932Z]    at Microsoft.DurableTask.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
[2024-04-11T12:13:03.933Z]    at Microsoft.DurableTask.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
[2024-04-11T12:13:03.935Z]    at Microsoft.DurableTask.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
[2024-04-11T12:13:03.935Z]    at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
[2024-04-11T12:13:03.937Z]    at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|424_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
```

**Comment by davidmrdavid** [comment]
This may be a duplicate of: https://github.com/microsoft/durabletask-dotnet/issues/282

**Comment by sebastianburckhardt** [comment]
Netherite is not yet supported for the dotnet isolated runtime.

We are planning to add this with this PR: https://github.com/microsoft/durabletask-netherite/pull/358
