### ISSUE TITLE
ProcessEventsAsync Handler not set

### ISSUE THREAD

**Issue by Selekena** [microsoft/durabletask-netherite#430]
We are setting up our .Net app with netherite against a storage account and eventhub. We get an exception when our app attempts to start. 

System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot begin processing without the ProcessEventAsync handler set.
  Source=Azure.Messaging.EventHubs.Processor
  StackTrace:
   at Azure.Messaging.EventHubs.EventProcessorClient.<StartProcessingInternalAsync>d__73.MoveNext()
   at Azure.Messaging.EventHubs.EventProcessorClient.<StartProcessingAsync>d__54.MoveNext()
   at DurableTask.Netherite.EventHubsTransport.EventHubsPartitionManager.<StartHostingPartitionsAsync>d__16.MoveNext()
   at DurableTask.Netherite.EventHubsTransport.EventHubsTransport.<DurableTask-Netherite-ITransportLayer-StartWorkersAsync>d__39.MoveNext()
   at DurableTask.Netherite.NetheriteOrchestrationService.<StartWorkersAsync>d__94.MoveNext()
   at DurableTask.Netherite.NetheriteOrchestrationService.<>c__DisplayClass92_0`1.<<TryTransition>g__conditionalTransition|0>d.MoveNext()
   at DurableTask.Netherite.NetheriteOrchestrationService.<TryStartAsync>d__91.MoveNext()
   at DurableTask.Core.TaskHubWorker.<StartAsync>d__32.MoveNext()
   at Microsoft.Azure.EdgeProvisioning.Common.Workflow.Engine.WorkflowWorker.<StartAsync>d__10.MoveNext()
   at Microsoft.Azure.EdgeProvisioning.Common.Workflow.Engine.WorkflowEngine.<StartAsync>d__5.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)
   at Program.<Main>
  This exception was originally thrown at this call stack:
    [External Code]
    Program.<Main>$(string[]) in Program.cs

We supposed (and I get this from reading the source here) that this should be handled by Netherite already. Our other apps did not need to register one. Is this a netherite issue or are not passing something into the Taskhubworker startAsync?

**Comment by sebastianburckhardt** [comment]
It looks to me like there is a line missing from the second constructor in `EventProcessorHost.cs`. By all appearances, a simple copy-paste mistake that got missed in the testing because all the tests use the other constructor.

I will test this to confirm and submit a PR to fix.

**Comment by sebastianburckhardt** [comment]
Fixed with latest release.
