### ISSUE TITLE
starting a new orchestration via IDurableClient times out

### ISSUE THREAD

**Issue by JackSkylark** [microsoft/durabletask-netherite#45]
I have a very simple `HttpTrigger` that is attempting to start an orchestration. However, the orchestration never starts and the http request eventually times out. This works as expected in the default durable backend.

```
public class HttpTrigger
{
    private readonly ILogger<HttpTrigger> _logger;

    public HttpTrigger(
        ILogger<HttpTrigger> logger)
    {
        _logger = logger;
    }

    [FunctionName("HttpTrigger")]
    public async Task<IActionResult> RunAsync(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "test")] HttpRequest req,
        [DurableClient] IDurableClient durableClient)
    {
        await durableClient.StartNewAsync(
            nameof(ExecutionTestOrchestration));

        return new OkObjectResult("Enqueued");
    }
}
```

**Comment by sebastianburckhardt** [comment]
Are you running this locally? What OS are you using? Do you see any error messages in the console?

**Comment by JackSkylark** [comment]
Yes, I am running locally. Windows 10 (10.0.19042 Build 19042). I never see any error messages.

**Comment by sebastianburckhardt** [comment]
Trying to repro on my own machine, but no success so far. Your code works as it should for me (see details about what I tested below). Not sure where things are going wrong.

Did you try to run the [hello sample](https://microsoft.github.io/durabletask-netherite/#/hello-sample)? Did that work?

To make progress, I may need more information. If you could add the following flags to host.json and send me the console output of the terminal that is running func.exe, it may help:
```
  "logging": {
    "logLevel": {
      // --- the levels below are used to control the Netherite tracing.
      "DurableTask.Netherite": "Debug",
      "DurableTask.Netherite.FasterStorage": "Debug",
      "DurableTask.Netherite.EventHubsTransport": "Debug",
      "DurableTask.Netherite.Events": "Debug",
      "DurableTask.Netherite.WorkItems": "Debug"
    },
  },
```

Another option is to deploy to a premium plan and tell me the region and name of the function app, then I can look at the generated telemetry directly.

## What I tested

 I copied your code into the Hello sample at `durabletask-netherite\samples\Hello\Hello.csproj` and added an orchestration, 
```csharp
  [FunctionName(nameof(ExecutionTestOrchestration))]
        public static Task ExecutionTestOrchestration([OrchestrationTrigger] IDurableOrchestrationContext context, ILogger logger)
        {
            logger.LogWarning("EXECUTED");
            return Task.CompletedTask;
        }
```
After compiling and setting `AzureWebJobsStorage` and `EventHubsConnection` environment variables, I go to the folder `samples\Hello\bin\Release\netcoreapp3.1` and call `func.exe`. Then `curl http://localhost:7071/api/test -d ""` from another terminal. The output looks like this:
```
Azure Functions Core Tools
Core Tools Version:       3.0.3442 Commit hash: 6bfab24b2743f8421475d996402c398d2fe4a9e0  (64-bit)
Function Runtime Version: 3.0.15417.0

[2021-06-17T13:37:32.895Z] Found C:\home\git\durabletask-netherite\samples\Hello\Hello.csproj. Using for user secrets file configuration.
Skipping 'AzureWebJobsStorage' from local settings as it's already defined in current environment variables.
Skipping 'EventHubsConnection' from local settings as it's already defined in current environment variables.

Functions:

        HttpTrigger: [POST] http://localhost:7071/api/test

        ExecutionTestOrchestration: orchestrationTrigger

For detailed output, run func with --verbose flag.
[2021-06-17T13:37:42.570Z] Host lock lease acquired by instance ID '000000000000000000000000D9DB239F'.
[2021-06-17T13:37:56.346Z] Executing 'HttpTrigger' (Reason='This function was programmatically called via the host APIs.', Id=810e2cfe-31c7-42b2-b30f-0c55214ca04c)
[2021-06-17T13:37:56.858Z] Executing 'ExecutionTestOrchestration' (Reason='(null)', Id=257588ee-f5dd-42d7-8dd1-5a0a83ec2955)
[2021-06-17T13:37:56.870Z] EXECUTED
[2021-06-17T13:37:56.887Z] Executed 'ExecutionTestOrchestration' (Succeeded, Id=257588ee-f5dd-42d7-8dd1-5a0a83ec2955, Duration=21ms)
[2021-06-17T13:37:56.915Z] Executed 'HttpTrigger' (Succeeded, Id=810e2cfe-31c7-42b2-b30f-0c55214ca04c, Duration=631ms)
```

**Comment by sebastianburckhardt** [comment]
Could be related to #55.

**Comment by shibayan** [comment]
I had the same problem with an application that was already deployed to Azure. The Application Insights log shows that the orchestrator was started correctly, but then something goes wrong and it seems to be taking longer than 20 seconds.

The frequency of occurrence is quite high and reproducible in my environment.

### Environment

- Durable Functions : `2.5.0`
- Netherite : `0.4.0-alpha`
- Azure Functions Host : `3.1.0`
- App Service Plan : EP2
- Event Hubs Namespace: Standard / TU1

### Code

```csharp
public static class Function1
{
    [FunctionName("Function1")]
    public static async Task<List<string>> RunOrchestrator(
        [OrchestrationTrigger] IDurableOrchestrationContext context)
    {
        var outputs = new List<string>();

        // Replace "hello" with the name of your Durable Activity Function.
        outputs.Add(await context.CallActivityAsync<string>("Function1_Hello", "Tokyo"));
        outputs.Add(await context.CallActivityAsync<string>("Function1_Hello", "Seattle"));
        outputs.Add(await context.CallActivityAsync<string>("Function1_Hello", "London"));
        outputs.Add(await context.CallActivityAsync<string>("Function1_Hello", "Amsterdam"));
        outputs.Add(await context.CallActivityAsync<string>("Function1_Hello", "Mumbai"));

        // returns ["Hello Tokyo!", "Hello Seattle!", "Hello London!"]
        return outputs;
    }

    [FunctionName("Function1_Hello")]
    public static string SayHello([ActivityTrigger] string name, ILogger log)
    {
        log.LogInformation($"Saying hello to {name}.");
        return $"Hello {name}!";
    }

    [FunctionName("Function1_HttpStart")]
    public static async Task<HttpResponseMessage> HttpStart(
        [HttpTrigger(AuthorizationLevel.Function, "get")] HttpRequestMessage req,
        [DurableClient] IDurableOrchestrationClient starter,
        ILogger log)
    {
        // Function input comes from the request content.
        string instanceId = await starter.StartNewAsync("Function1", null);

        log.LogInformation($"Started orchestration with ID = '{instanceId}'.");

        return starter.CreateCheckStatusResponse(req, instanceId);
    }
}
```

### Host Configuration

```json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": false,
        "excludedTypes": "Request"
      }
    },
    "logLevel": {
      "Function": "Debug",
      "Host.Triggers.DurableTask": "Debug",
      "DurableTask.Netherite": "Debug",
      "DurableTask.Netherite.FasterStorage": "Debug",
      "DurableTask.Netherite.EventHubsTransport": "Warning",
      "DurableTask.Netherite.Events": "Debug",
      "DurableTask.Netherite.WorkItems": "Debug"
    }
  },
  "extensions": {
    "durableTask": {
      "useGracefulShutdown": true,
      "storageProvider": {
        "type": "Netherite",
        "StorageConnectionName": "AzureWebJobsStorage",
        "EventHubsConnectionName": "EventHubsConnection"
      }
    }
  }
}
```

### Application Insights Log

![image](https://user-images.githubusercontent.com/1356444/125616015-bd331b0e-e768-4e84-935a-4fcfbcde99b1.png)

![image](https://user-images.githubusercontent.com/1356444/125616407-8bb9c87f-51ea-4c36-97d6-c9213ba1e121.png)

**Comment by shibayan** [comment]
It seems to have stopped happening after changing the Azure Functions Platform bitness to 64bit and initializing the storage account.

When the response was unusually slow, the following exceptions occurred continuously.

```
Part06 !!! Encountered exception while working on store in StoreWorker.Process: FASTER.core.FasterException: Overflow in AddressInfo - consider running the program in x64 mode for larger address space support
   at FASTER.core.AddressInfo.set_Address(Int64 value)
   at FASTER.core.GenericAllocator`2.WriteAsync[TContext](Int64 flushPage, UInt64 alignedDestinationAddress, UInt32 numBytesToWrite, DeviceIOCompletionCallback callback, PageAsyncFlushResult`1 asyncResult, IDevice device, IDevice objlogDevice, Int64 intendedDestinationPage, Int64[] localSegmentOffsets)
   at FASTER.core.GenericAllocator`2.WriteAsync[TContext](Int64 flushPage, DeviceIOCompletionCallback callback, PageAsyncFlushResult`1 asyncResult)
   at FASTER.core.AllocatorBase`2.AsyncFlushPages(Int64 fromAddress, Int64 untilAddress)
   at FASTER.core.AllocatorBase`2.OnPagesMarkedReadOnly(Int64 newSafeReadOnlyAddress)
   at FASTER.core.AllocatorBase`2.<>c__DisplayClass88_0.<ShiftReadOnlyToTail>b__0()
   at FASTER.core.LightEpoch.BumpCurrentEpoch(Action onDrain)
   at FASTER.core.AllocatorBase`2.ShiftReadOnlyToTail(Int64& tailAddress, SemaphoreSlim& notifyDone)
   at FASTER.core.FoldOverCheckpointTask.GlobalBeforeEnteringState[Key,Value](SystemState next, FasterKV`2 faster)
   at FASTER.core.SynchronizationStateMachineBase.GlobalBeforeEnteringState[Key,Value](SystemState next, FasterKV`2 faster)
   at FASTER.core.FasterKV`2.GlobalStateMachineStep(SystemState expectedState)
   at FASTER.core.VersionChangeTask.OnThreadState[Key,Value,Input,Output,Context,FasterSession](SystemState current, SystemState prev, FasterKV`2 faster, FasterExecutionContext`3 ctx, FasterSession fasterSession, List`1 valueTasks, CancellationToken token)
   at FASTER.core.SynchronizationStateMachineBase.OnThreadEnteringState[Key,Value,Input,Output,Context,FasterSession](SystemState current, SystemState prev, FasterKV`2 faster, FasterExecutionContext`3 ctx, FasterSession fasterSession, List`1 valueTasks, CancellationToken token)
   at FASTER.core.FasterKV`2.ThreadStateMachineStep[Input,Output,Context,FasterSession](FasterExecutionContext`3 ctx, FasterSession fasterSession, List`1 valueTasks, CancellationToken token)
   at FASTER.core.ClientSession`6.Refresh()
   at DurableTask.Netherite.Faster.FasterKV.StartStoreCheckpoint(Int64 commitLogPosition, Int64 inputQueuePosition) in C:\source\durabletask-netherite\src\DurableTask.Netherite\StorageProviders\Faster\FasterKV.cs:line 182
   at DurableTask.Netherite.Faster.StoreWorker.Process(IList`1 batch) in C:\source\durabletask-netherite\src\DurableTask.Netherite\StorageProviders\Faster\StoreWorker.cs:line 327 terminatePartition=True
```

**Comment by sebastianburckhardt** [comment]
This makes sense! The FASTER backend requires 64bit mode because it uses large page blobs.
I did not catch this because my tests are all running on 64bit.

I think I need to:
- Update the documentation to state 64bit as a requirement for Netherite
- Update the code so it throws a more descriptive exception when running 32bit

Thanks for figuring this out!

**Comment by sebastianburckhardt** [comment]
For now I am assuming this issue was caused by using 32bit instead of 64bit.

@JackSkylark, let me know if using 64bit runtime does not solve your problem.
