### ISSUE TITLE
ScaleMonitor.GetMetricsAsync() failed: Microsoft.Azure.Cosmos.Table.StorageException: Not Found

### ISSUE THREAD

**Issue by marcduiker** [microsoft/durabletask-netherite#74]
We're trying to change an existing Durable Functions App to use Netherite but seeing a lot of errors in the logs when this is deployed to Azure. None of the functions appear to be running due to the errors.

## Traces & Exceptions

After the Function App starts the _NetheriteOrchestrationService_ is created succesfully:

`NetheriteOrchestrationService created, workerId=pd1sdwk00021W, processorCount=1, transport=EventHubs, storage=Faster`

Then we see these for every Orchestator, Activity and Entity function in the app:

`The listener for function '<FunctionName>' was unable to start.` (Severity 3)

Then we see dozens of these:

`Netherite autoscaler recommends: None from: 2 because: missing metrics` (Severity 1)

Then retries of starting the listeners (Attempt 1 and 2):

`Retrying to start listener for function '<FunctionName> (Attempt 1)` (Severity 1)

Then

```
IScaleMonitor.GetMetricsAsync() failed: Microsoft.Azure.Cosmos.Table.StorageException: Not Found
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken callerCancellationToken)
   at DurableTask.Netherite.Scaling.AzureTableLoadMonitor.QueryAsync(CancellationToken cancellationToken) in C:\source\durabletask-netherite\src\DurableTask.Netherite\Scaling\AzureTableLoadMonitor.cs:line 84
   at DurableTask.Netherite.Scaling.ScalingMonitor.CollectMetrics() in C:\source\durabletask-netherite\src\DurableTask.Netherite\Scaling\ScalingMonitor.cs:line 110
   at DurableTask.Netherite.AzureFunctions.NetheriteProvider.ScaleMonitor.GetMetricsAsync() in C:\source\durabletask-netherite\src\DurableTask.Netherite.AzureFunctions\NetheriteProvider.cs:line 170
Request Information
RequestID:0471c8ac-e002-0043-5d38-b58660000000
RequestDate:Wed, 29 Sep 2021 13:47:25 GMT
StatusMessage:Not Found
ErrorCode:
ErrorMessage:The table specified does not exist.
RequestId:0471c8ac-e002-0043-5d38-b58660000000
Time:2021-09-29T13:47:25.4358594Z
```

Followed by hundreds of these:

```
IScaleMonitor.GetScaleStatus() failed: System.ArgumentNullException: Buffer cannot be null. (Parameter 'buffer')
   at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
   at DurableTask.Netherite.AzureFunctions.NetheriteProvider.ScaleMonitor.GetScaleStatusCore(Int32 workerCount, NetheriteScaleMetrics[] metrics) in C:\source\durabletask-netherite\src\DurableTask.Netherite.AzureFunctions\NetheriteProvider.cs:line 211 
```
## Infra & configuration

We're running a .NET Core 3.1 Function App on an  _EP1_ SKU with _Runtime Scaling Monitoring_ enabled. We're also using VNETs and private endpoints.

This is the hosts.json:

```json
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
        "storageProvider": {
          "type" : "Netherite",
          "partitionCount": 12,
          "StorageConnectionName": "AzureWebJobsStorage",
          "EventHubsConnectionName": "EventHubsConnection"
        },
        "hubName": "%TaskHubName%",
        "useGracefulShutdown": true,
        "LogLevelLimit": "Debug",
        "StorageLogLevelLimit": "Debug",
        "TransportLogLevelLimit": "Debug",
        "EventLogLevelLimit": "Debug",
        "WorkItemLogLevelLimit": "Debug",
        "TraceToConsole": false,
        "TraceToBlob": false
    }
  },
  "functionTimeout": "00:30:00",
  "logging": {
    "logLevel": {
      "Host.Results": "Warning",
      "Host.Executor": "Warning",
      "default": "Information",
      "Metrics": "Information",
      "Host.Triggers.DurableTask": "Warning",
      "Host.Triggers.DurableTask.AzureStorage": "Warning",
      "Function": "Warning",
      "Microsoft": "Warning",
      "Worker": "Warning",
      "DurableTask": "Warning",
      "DurableTask.AzureStorage": "Warning",
      "DurableTask.Core": "Warning",
      "System.Net.Http.HttpClient": "Information",
      "DurableTask.Netherite": "Information",
      "DurableTask.Netherite.FasterStorage": "Warning",
      "DurableTask.Netherite.EventHubsTransport": "Warning",
      "DurableTask.Netherite.Events": "Warning",
      "DurableTask.Netherite.WorkItems": "Warning"
    },
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes" : "Event"
      }
    }
  }
}
```

This is the csproj:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <StartDevelopmentStorage>false</StartDevelopmentStorage>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Security.KeyVault.Certificates" Version="4.2.0"/>
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.2.0"/>
    <PackageReference Include="Azure.Storage.Queues" Version="12.8.0"/>
    <PackageReference Include="Bogus" Version="33.1.1"/>
    <PackageReference Include="IdentityModel.AspNetCore" Version="3.0.0"/>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0"/>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.5"/>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="3.1.19"/>
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="3.1.19"/>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13"/>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.5.1"/>
    <PackageReference Include="Refit" Version="5.2.4"/>
    <PackageReference Include="Refit.HttpClientFactory" Version="5.2.4"/>
    <PackageReference Include="FluentValidation" Version="10.3.3"/>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.18.0"/>
    <PackageReference Include="Dapper" Version="2.0.90"/>
    <PackageReference Include="System.Data.SqlClient" Version="4.8.2"/>
    <PackageReference Include="Dapper.SimpleCRUD" Version="2.3.0"/>
    <PackageReference Include="Azure.Identity" Version="1.4.1"/>
    <PackageReference Include="Microsoft.Azure.WebJobs.Logging.ApplicationInsights" Version="3.0.30"/>
    <PackageReference Include="Microsoft.Azure.DurableTask.Netherite.AzureFunctions" Version="0.5.0-alpha"/>
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

I don't see a table named _DurableTaskPartitions_ which should be there according to the docs. Also no EventHubs are created in the namespace. Any idea about the root cause and how to solve this?

**Comment by olitomlinson** [comment]
@marcduiker Are you on Consumption Plan by any chance?

**Comment by marcduiker** [comment]
> @marcduiker Are you on Consumption Plan by any chance?

No Premium (EP1)

**Comment by sebastianburckhardt** [comment]
We have more tracing in place now, with the latest version 0.6.0-alpha. If you see the same problem again, let me know and I will take a look.

**Comment by marcduiker** [comment]
Thank you @sebastianburckhardt!

@mivano perhaps something for you to look into?

**Comment by sebastianburckhardt** [comment]
Closing this due to inactivity. If you want to reconsider, just reopen.
